# Form implementation generated from reading ui file 'window/Chagethemnesk_checkWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Chagethemnesk_checkWin(object):
    def setupUi(self, Chagethemnesk_checkWin):
        Chagethemnesk_checkWin.setObjectName("Chagethemnesk_checkWin")
        Chagethemnesk_checkWin.resize(497, 617)
        self.label_2 = QtWidgets.QLabel(parent=Chagethemnesk_checkWin)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 50pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"font-size: 50px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textEdit_15 = QtWidgets.QTextEdit(parent=Chagethemnesk_checkWin)
        self.textEdit_15.setGeometry(QtCore.QRect(50, 370, 251, 41))
        self.textEdit_15.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #a0d18c;\n"
"\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"  color: #2d9fd9;")
        self.textEdit_15.setObjectName("textEdit_15")
        self.textEdit_13 = QtWidgets.QTextEdit(parent=Chagethemnesk_checkWin)
        self.textEdit_13.setGeometry(QtCore.QRect(190, 120, 291, 71))
        self.textEdit_13.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #a0d18c;\n"
"\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"  color: #2d9fd9;")
        self.textEdit_13.setObjectName("textEdit_13")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=Chagethemnesk_checkWin)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 390, 16, 17))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_5 = QtWidgets.QCheckBox(parent=Chagethemnesk_checkWin)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 500, 16, 17))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.textEdit_17 = QtWidgets.QTextEdit(parent=Chagethemnesk_checkWin)
        self.textEdit_17.setGeometry(QtCore.QRect(50, 490, 251, 41))
        self.textEdit_17.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #a0d18c;\n"
"\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"  color: #2d9fd9;")
        self.textEdit_17.setObjectName("textEdit_17")
        self.textEdit_14 = QtWidgets.QTextEdit(parent=Chagethemnesk_checkWin)
        self.textEdit_14.setGeometry(QtCore.QRect(50, 310, 251, 41))
        self.textEdit_14.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #a0d18c;\n"
"\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"  color: #2d9fd9;")
        self.textEdit_14.setObjectName("textEdit_14")
        self.textEdit_19 = QtWidgets.QTextEdit(parent=Chagethemnesk_checkWin)
        self.textEdit_19.setGeometry(QtCore.QRect(50, 430, 251, 41))
        self.textEdit_19.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #a0d18c;\n"
"\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"  color: #2d9fd9;")
        self.textEdit_19.setObjectName("textEdit_19")
        self.checkBox = QtWidgets.QCheckBox(parent=Chagethemnesk_checkWin)
        self.checkBox.setGeometry(QtCore.QRect(20, 260, 16, 17))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label_6 = QtWidgets.QLabel(parent=Chagethemnesk_checkWin)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(0, 110, 501, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 25pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"padding-right: 300px;\n"
"\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=Chagethemnesk_checkWin)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 320, 16, 17))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.textEdit_16 = QtWidgets.QTextEdit(parent=Chagethemnesk_checkWin)
        self.textEdit_16.setGeometry(QtCore.QRect(50, 250, 251, 41))
        self.textEdit_16.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #a0d18c;\n"
"\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"  color: #2d9fd9;")
        self.textEdit_16.setObjectName("textEdit_16")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=Chagethemnesk_checkWin)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 440, 16, 17))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Chagethemnesk_checkWin)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 540, 121, 41))
        self.pushButton_2.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=Chagethemnesk_checkWin)
        self.label.setGeometry(QtCore.QRect(20, 220, 461, 21))
        self.label.setStyleSheet("font:  16pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_6.raise_()
        self.label_2.raise_()
        self.textEdit_15.raise_()
        self.textEdit_13.raise_()
        self.checkBox_3.raise_()
        self.checkBox_5.raise_()
        self.textEdit_17.raise_()
        self.textEdit_14.raise_()
        self.textEdit_19.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.textEdit_16.raise_()
        self.checkBox_4.raise_()
        self.pushButton_2.raise_()
        self.label.raise_()

        self.retranslateUi(Chagethemnesk_checkWin)
        QtCore.QMetaObject.connectSlotsByName(Chagethemnesk_checkWin)

    def retranslateUi(self, Chagethemnesk_checkWin):
        _translate = QtCore.QCoreApplication.translate
        Chagethemnesk_checkWin.setWindowTitle(_translate("Chagethemnesk_checkWin", "Chage test neskolko"))
        self.label_2.setText(_translate("Chagethemnesk_checkWin", "Тест"))
        self.textEdit_15.setHtml(_translate("Chagethemnesk_checkWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_13.setHtml(_translate("Chagethemnesk_checkWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_17.setHtml(_translate("Chagethemnesk_checkWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_14.setHtml(_translate("Chagethemnesk_checkWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_19.setHtml(_translate("Chagethemnesk_checkWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("Chagethemnesk_checkWin", "Вопрос:"))
        self.textEdit_16.setHtml(_translate("Chagethemnesk_checkWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("Chagethemnesk_checkWin", "Сохранить"))
        self.label.setText(_translate("Chagethemnesk_checkWin", "Ответы:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Chagethemnesk_checkWin = QtWidgets.QDialog()
    ui = Ui_Chagethemnesk_checkWin()
    ui.setupUi(Chagethemnesk_checkWin)
    Chagethemnesk_checkWin.show()
    sys.exit(app.exec())
