# Form implementation generated from reading ui file 'window/CheckthemsWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_checkthemsWin(object):
    def setupUi(self, checkthemsWin):
        checkthemsWin.setObjectName("checkthemsWin")
        checkthemsWin.resize(497, 617)
        self.label_2 = QtWidgets.QLabel(parent=checkthemsWin)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-20, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 40pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=checkthemsWin)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 560, 121, 41))
        self.pushButton_3.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(parent=checkthemsWin)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(0, 90, 501, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 20pt \"Times New Roman\";\n"
"\n"
"\n"
"text-align: center;\n"
"\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=checkthemsWin)
        self.scrollArea.setGeometry(QtCore.QRect(10, 130, 471, 421))
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(checkthemsWin)
        QtCore.QMetaObject.connectSlotsByName(checkthemsWin)

    def retranslateUi(self, checkthemsWin):
        _translate = QtCore.QCoreApplication.translate
        checkthemsWin.setWindowTitle(_translate("checkthemsWin", "checkthems"))
        self.label_2.setText(_translate("checkthemsWin", "Проверка"))
        self.pushButton_3.setText(_translate("checkthemsWin", "Назад"))
        self.label_3.setText(_translate("checkthemsWin", "ФИО"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    checkthemsWin = QtWidgets.QDialog()
    ui = Ui_checkthemsWin()
    ui.setupUi(checkthemsWin)
    checkthemsWin.show()
    sys.exit(app.exec())
