# Form implementation generated from reading ui file 'window/LoginWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWin(object):
    def setupUi(self, LoginWin):
        LoginWin.setObjectName("LoginWin")
        LoginWin.resize(497, 617)
        self.textEdit = QtWidgets.QTextEdit(parent=LoginWin)
        self.textEdit.setGeometry(QtCore.QRect(140, 190, 221, 41))
        self.textEdit.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #000000;\n"
"font: 12pt \"Times New Roman\";\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;")
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(parent=LoginWin)
        self.label.setGeometry(QtCore.QRect(150, 170, 51, 21))
        self.label.setStyleSheet("font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=LoginWin)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 50pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"font-size: 50px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=LoginWin)
        self.textEdit_2.setGeometry(QtCore.QRect(140, 270, 221, 41))
        self.textEdit_2.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #000000;\n"
"font: 12pt \"Times New Roman\";\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=LoginWin)
        self.label_3.setGeometry(QtCore.QRect(150, 250, 61, 21))
        self.label_3.setStyleSheet("font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=LoginWin)
        self.pushButton.setGeometry(QtCore.QRect(140, 390, 231, 41))
        self.pushButton.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=LoginWin)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 560, 181, 41))
        self.pushButton_2.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton = QtWidgets.QRadioButton(parent=LoginWin)
        self.radioButton.setGeometry(QtCore.QRect(150, 330, 181, 17))
        self.radioButton.setStyleSheet("text-align: center;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";\n"
"")
        self.radioButton.setObjectName("radioButton")
        self.label_4 = QtWidgets.QLabel(parent=LoginWin)
        self.label_4.setGeometry(QtCore.QRect(130, 360, 251, 31))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(parent=LoginWin)
        self.label_8.setGeometry(QtCore.QRect(200, 170, 211, 21))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=LoginWin)
        self.label_9.setGeometry(QtCore.QRect(210, 250, 211, 21))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(LoginWin)
        QtCore.QMetaObject.connectSlotsByName(LoginWin)

    def retranslateUi(self, LoginWin):
        _translate = QtCore.QCoreApplication.translate
        LoginWin.setWindowTitle(_translate("LoginWin", "Login"))
        self.textEdit.setHtml(_translate("LoginWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("LoginWin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Логин</span></p></body></html>"))
        self.label_2.setText(_translate("LoginWin", "Войти"))
        self.textEdit_2.setHtml(_translate("LoginWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("LoginWin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Пароль</span></p></body></html>"))
        self.pushButton.setText(_translate("LoginWin", "Войти"))
        self.pushButton_2.setToolTip(_translate("LoginWin", "Перейдите на страницу с регистрацией"))
        self.pushButton_2.setText(_translate("LoginWin", "Зарегистрироваться"))
        self.radioButton.setToolTip(_translate("LoginWin", "Зайти как учитель"))
        self.radioButton.setText(_translate("LoginWin", "Преподаватель"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWin = QtWidgets.QDialog()
    ui = Ui_LoginWin()
    ui.setupUi(LoginWin)
    LoginWin.show()
    sys.exit(app.exec())
