# Form implementation generated from reading ui file 'window/Mejdu_studWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mejdu_studWin(object):
    def setupUi(self, Mejdu_studWin):
        Mejdu_studWin.setObjectName("Mejdu_studWin")
        Mejdu_studWin.resize(497, 617)
        self.label_2 = QtWidgets.QLabel(parent=Mejdu_studWin)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-20, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 50pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Mejdu_studWin)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 510, 251, 71))
        self.pushButton_3.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Mejdu_studWin)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 320, 251, 101))
        self.pushButton_4.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Mejdu_studWin)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 130, 251, 101))
        self.pushButton_5.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Mejdu_studWin)
        QtCore.QMetaObject.connectSlotsByName(Mejdu_studWin)

    def retranslateUi(self, Mejdu_studWin):
        _translate = QtCore.QCoreApplication.translate
        Mejdu_studWin.setWindowTitle(_translate("Mejdu_studWin", "Выбор"))
        self.label_2.setText(_translate("Mejdu_studWin", "Тема"))
        self.pushButton_3.setToolTip(_translate("Mejdu_studWin", "Вернуться к темам"))
        self.pushButton_3.setText(_translate("Mejdu_studWin", "Назад"))
        self.pushButton_4.setToolTip(_translate("Mejdu_studWin", "Пройти задание"))
        self.pushButton_4.setText(_translate("Mejdu_studWin", "Практика"))
        self.pushButton_5.setToolTip(_translate("Mejdu_studWin", "Почитать теорию"))
        self.pushButton_5.setText(_translate("Mejdu_studWin", "Теория"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mejdu_studWin = QtWidgets.QDialog()
    ui = Ui_Mejdu_studWin()
    ui.setupUi(Mejdu_studWin)
    Mejdu_studWin.show()
    sys.exit(app.exec())
