# Form implementation generated from reading ui file 'window/Prac_makeWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Prac_makeWin(object):
    def setupUi(self, Prac_makeWin):
        Prac_makeWin.setObjectName("Prac_makeWin")
        Prac_makeWin.resize(497, 617)
        self.label_6 = QtWidgets.QLabel(parent=Prac_makeWin)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(-10, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 40pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"\n"
"\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(parent=Prac_makeWin)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 451, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 30pt \"Times New Roman\";\n"
"\n"
"\n"
"text-align: center;\n"
"\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(parent=Prac_makeWin)
        self.textEdit.setGeometry(QtCore.QRect(10, 190, 481, 331))
        self.textEdit.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #a0d18c;\n"
"\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"  color: #2d9fd9;")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Prac_makeWin)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 560, 121, 41))
        self.pushButton_2.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Prac_makeWin)
        QtCore.QMetaObject.connectSlotsByName(Prac_makeWin)

    def retranslateUi(self, Prac_makeWin):
        _translate = QtCore.QCoreApplication.translate
        Prac_makeWin.setWindowTitle(_translate("Prac_makeWin", "Prac_make"))
        self.label_6.setText(_translate("Prac_makeWin", "Практика"))
        self.label_3.setText(_translate("Prac_makeWin", "Задание"))
        self.textEdit.setHtml(_translate("Prac_makeWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("Prac_makeWin", "Далее"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Prac_makeWin = QtWidgets.QDialog()
    ui = Ui_Prac_makeWin()
    ui.setupUi(Prac_makeWin)
    Prac_makeWin.show()
    sys.exit(app.exec())
