# Form implementation generated from reading ui file 'window/Prac_provercWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pract_provercWin(object):
    def setupUi(self, pract_provercWin):
        pract_provercWin.setObjectName("pract_provercWin")
        pract_provercWin.resize(497, 617)
        self.pushButton_3 = QtWidgets.QPushButton(parent=pract_provercWin)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 560, 121, 41))
        self.pushButton_3.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(parent=pract_provercWin)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-20, 0, 521, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 40pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_13 = QtWidgets.QLabel(parent=pract_provercWin)
        self.label_13.setGeometry(QtCore.QRect(330, 560, 101, 41))
        self.label_13.setStyleSheet("font: 15pt \"Times New Roman\";")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=pract_provercWin)
        self.textEdit_2.setGeometry(QtCore.QRect(440, 570, 31, 31))
        self.textEdit_2.setStyleSheet("\n"
"\n"
"  border: 1px solid black;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(parent=pract_provercWin)
        self.label.setGeometry(QtCore.QRect(350, 520, 141, 41))
        self.label.setStyleSheet("font: 15pt \"Times New Roman\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(parent=pract_provercWin)
        self.label_7.setGeometry(QtCore.QRect(10, 510, 311, 41))
        self.label_7.setStyleSheet("font: 15pt \"Times New Roman\";")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.textBrowser = QtWidgets.QTextBrowser(parent=pract_provercWin)
        self.textBrowser.setGeometry(QtCore.QRect(10, 180, 481, 321))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=pract_provercWin)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 80, 481, 81))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_2.raise_()
        self.pushButton_3.raise_()
        self.label_13.raise_()
        self.textEdit_2.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()

        self.retranslateUi(pract_provercWin)
        QtCore.QMetaObject.connectSlotsByName(pract_provercWin)

    def retranslateUi(self, pract_provercWin):
        _translate = QtCore.QCoreApplication.translate
        pract_provercWin.setWindowTitle(_translate("pract_provercWin", "Proverca"))
        self.pushButton_3.setToolTip(_translate("pract_provercWin", "Сохранить и выйти"))
        self.pushButton_3.setText(_translate("pract_provercWin", "Назад"))
        self.label_2.setText(_translate("pract_provercWin", "Тема 1"))
        self.label_13.setText(_translate("pract_provercWin", "Оценка:"))
        self.textEdit_2.setHtml(_translate("pract_provercWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("pract_provercWin", "Балл тест:"))
        self.label_7.setText(_translate("pract_provercWin", "ФИО"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pract_provercWin = QtWidgets.QDialog()
    ui = Ui_pract_provercWin()
    ui.setupUi(pract_provercWin)
    pract_provercWin.show()
    sys.exit(app.exec())
