# Form implementation generated from reading ui file 'window/Predmet_studWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Predmet_studWin(object):
    def setupUi(self, Predmet_studWin):
        Predmet_studWin.setObjectName("Predmet_studWin")
        Predmet_studWin.resize(497, 617)
        self.label_2 = QtWidgets.QLabel(parent=Predmet_studWin)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-20, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 50pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"font-size: 50px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_11 = QtWidgets.QPushButton(parent=Predmet_studWin)
        self.pushButton_11.setGeometry(QtCore.QRect(410, 10, 81, 71))
        self.pushButton_11.setStyleSheet(" background-color: grey; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"outline: none;\n"
"\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";\n"
"")
        self.pushButton_11.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logout_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.scrollArea = QtWidgets.QScrollArea(parent=Predmet_studWin)
        self.scrollArea.setGeometry(QtCore.QRect(10, 140, 471, 451))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 469, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Predmet_studWin)
        QtCore.QMetaObject.connectSlotsByName(Predmet_studWin)

    def retranslateUi(self, Predmet_studWin):
        _translate = QtCore.QCoreApplication.translate
        Predmet_studWin.setWindowTitle(_translate("Predmet_studWin", "Предмет"))
        self.label_2.setText(_translate("Predmet_studWin", "Предметы"))
        self.pushButton_11.setToolTip(_translate("Predmet_studWin", "Выход"))
        self.pushButton_11.setWhatsThis(_translate("Predmet_studWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Predmet_studWin = QtWidgets.QDialog()
    ui = Ui_Predmet_studWin()
    ui.setupUi(Predmet_studWin)
    Predmet_studWin.show()
    sys.exit(app.exec())
