# Form implementation generated from reading ui file 'window/Teoria_studWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Teoria_studWin(object):
    def setupUi(self, Teoria_studWin):
        Teoria_studWin.setObjectName("Teoria_studWin")
        Teoria_studWin.resize(497, 617)
        self.label_3 = QtWidgets.QLabel(parent=Teoria_studWin)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(-10, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 50pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Teoria_studWin)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 540, 251, 71))
        self.pushButton_3.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Teoria_studWin)
        self.textBrowser.setGeometry(QtCore.QRect(10, 110, 481, 421))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Teoria_studWin)
        QtCore.QMetaObject.connectSlotsByName(Teoria_studWin)

    def retranslateUi(self, Teoria_studWin):
        _translate = QtCore.QCoreApplication.translate
        Teoria_studWin.setWindowTitle(_translate("Teoria_studWin", "Теория"))
        self.label_3.setText(_translate("Teoria_studWin", "Теория"))
        self.pushButton_3.setText(_translate("Teoria_studWin", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Teoria_studWin = QtWidgets.QDialog()
    ui = Ui_Teoria_studWin()
    ui.setupUi(Teoria_studWin)
    Teoria_studWin.show()
    sys.exit(app.exec())
