# Form implementation generated from reading ui file 'window/Test_rad_studWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Test_rad_studWin(object):
    def setupUi(self, Test_rad_studWin):
        Test_rad_studWin.setObjectName("Test_rad_studWin")
        Test_rad_studWin.resize(497, 617)
        self.label_2 = QtWidgets.QLabel(parent=Test_rad_studWin)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 50pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"font-size: 50px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Test_rad_studWin)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 560, 121, 41))
        self.pushButton_3.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Test_rad_studWin)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 560, 121, 41))
        self.pushButton_2.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=Test_rad_studWin)
        self.scrollArea.setGeometry(QtCore.QRect(10, 170, 471, 361))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 469, 359))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.label_3 = QtWidgets.QLabel(parent=Test_rad_studWin)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(-10, 80, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 30pt \"Times New Roman\";\n"
"\n"
"\n"
"text-align: center;\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Test_rad_studWin)
        QtCore.QMetaObject.connectSlotsByName(Test_rad_studWin)

    def retranslateUi(self, Test_rad_studWin):
        _translate = QtCore.QCoreApplication.translate
        Test_rad_studWin.setWindowTitle(_translate("Test_rad_studWin", "Test odin otvet"))
        self.label_2.setText(_translate("Test_rad_studWin", "Тест"))
        self.pushButton_3.setText(_translate("Test_rad_studWin", "Назад"))
        self.pushButton_2.setText(_translate("Test_rad_studWin", "Далее"))
        self.label_3.setText(_translate("Test_rad_studWin", "Выберите только один ответ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Test_rad_studWin = QtWidgets.QDialog()
    ui = Ui_Test_rad_studWin()
    ui.setupUi(Test_rad_studWin)
    Test_rad_studWin.show()
    sys.exit(app.exec())
