# Form implementation generated from reading ui file 'window/Test_checkb_studWin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Test_checkb_studWin(object):
    def setupUi(self, Test_checkb_studWin):
        Test_checkb_studWin.setObjectName("Test_checkb_studWin")
        Test_checkb_studWin.resize(497, 617)
        self.label_2 = QtWidgets.QLabel(parent=Test_checkb_studWin)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-20, 0, 521, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 50pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"font-size: 50px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Test_checkb_studWin)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 560, 121, 41))
        self.pushButton_3.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Test_checkb_studWin)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 560, 121, 41))
        self.pushButton_2.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(parent=Test_checkb_studWin)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(0, 70, 501, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 20pt \"Times New Roman\";\n"
"\n"
"\n"
"text-align: center;\n"
"\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=Test_checkb_studWin)
        self.scrollArea.setGeometry(QtCore.QRect(10, 120, 471, 421))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 469, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Test_checkb_studWin)
        QtCore.QMetaObject.connectSlotsByName(Test_checkb_studWin)

    def retranslateUi(self, Test_checkb_studWin):
        _translate = QtCore.QCoreApplication.translate
        Test_checkb_studWin.setWindowTitle(_translate("Test_checkb_studWin", "Test neskolko otvetov"))
        self.label_2.setText(_translate("Test_checkb_studWin", "Тест"))
        self.pushButton_3.setText(_translate("Test_checkb_studWin", "Назад"))
        self.pushButton_2.setText(_translate("Test_checkb_studWin", "Далее"))
        self.label_3.setText(_translate("Test_checkb_studWin", "Выберите несколько ответов на вопрос."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Test_checkb_studWin = QtWidgets.QDialog()
    ui = Ui_Test_checkb_studWin()
    ui.setupUi(Test_checkb_studWin)
    Test_checkb_studWin.show()
    sys.exit(app.exec())
