# Form implementation generated from reading ui file 'window/Them1change_testrad.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Chagethemone_2radWin(object):
    def setupUi(self, Chagethemone_2radWin):
        Chagethemone_2radWin.setObjectName("Chagethemone_2radWin")
        Chagethemone_2radWin.resize(497, 617)
        self.label_2 = QtWidgets.QLabel(parent=Chagethemone_2radWin)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 50pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"font-size: 50px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Chagethemone_2radWin)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 560, 121, 41))
        self.pushButton_2.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Chagethemone_2radWin)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 560, 121, 41))
        self.pushButton_3.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=Chagethemone_2radWin)
        self.scrollArea.setGeometry(QtCore.QRect(10, 110, 471, 421))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 469, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Chagethemone_2radWin)
        QtCore.QMetaObject.connectSlotsByName(Chagethemone_2radWin)

    def retranslateUi(self, Chagethemone_2radWin):
        _translate = QtCore.QCoreApplication.translate
        Chagethemone_2radWin.setWindowTitle(_translate("Chagethemone_2radWin", "Chage them test rad"))
        self.label_2.setText(_translate("Chagethemone_2radWin", "Тест"))
        self.pushButton_2.setText(_translate("Chagethemone_2radWin", "Далее"))
        self.pushButton_3.setText(_translate("Chagethemone_2radWin", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Chagethemone_2radWin = QtWidgets.QDialog()
    ui = Ui_Chagethemone_2radWin()
    ui.setupUi(Chagethemone_2radWin)
    Chagethemone_2radWin.show()
    sys.exit(app.exec())
