# Form implementation generated from reading ui file 'window/ThemsWin_teacher.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ThemsWin_teacher(object):
    def setupUi(self, ThemsWin_teacher):
        ThemsWin_teacher.setObjectName("ThemsWin_teacher")
        ThemsWin_teacher.resize(497, 617)
        self.label_2 = QtWidgets.QLabel(parent=ThemsWin_teacher)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 50pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_11 = QtWidgets.QPushButton(parent=ThemsWin_teacher)
        self.pushButton_11.setGeometry(QtCore.QRect(410, 10, 71, 81))
        self.pushButton_11.setStyleSheet(" background-color: grey; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"outline: none;\n"
"\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";\n"
"")
        self.pushButton_11.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logout_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.scrollArea = QtWidgets.QScrollArea(parent=ThemsWin_teacher)
        self.scrollArea.setGeometry(QtCore.QRect(10, 120, 471, 421))
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_3 = QtWidgets.QPushButton(parent=ThemsWin_teacher)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 560, 121, 41))
        self.pushButton_3.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(ThemsWin_teacher)
        QtCore.QMetaObject.connectSlotsByName(ThemsWin_teacher)

    def retranslateUi(self, ThemsWin_teacher):
        _translate = QtCore.QCoreApplication.translate
        ThemsWin_teacher.setWindowTitle(_translate("ThemsWin_teacher", "ThemsWin_teacher"))
        self.label_2.setText(_translate("ThemsWin_teacher", "Темы"))
        self.pushButton_11.setToolTip(_translate("ThemsWin_teacher", "Выход"))
        self.pushButton_11.setWhatsThis(_translate("ThemsWin_teacher", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Exit</p></body></html>"))
        self.pushButton_3.setText(_translate("ThemsWin_teacher", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ThemsWin_teacher = QtWidgets.QDialog()
    ui = Ui_ThemsWin_teacher()
    ui.setupUi(ThemsWin_teacher)
    ThemsWin_teacher.show()
    sys.exit(app.exec())
