# Form implementation generated from reading ui file 'window/Them1chage_1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChegeThemOne_1Win(object):
    def setupUi(self, ChegeThemOne_1Win):
        ChegeThemOne_1Win.setObjectName("ChegeThemOne_1Win")
        ChegeThemOne_1Win.resize(497, 617)
        self.label_2 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-10, 40, 521, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 40pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"padding-right: 300px;\n"
"\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(parent=ChegeThemOne_1Win)
        self.textEdit.setGeometry(QtCore.QRect(200, 70, 291, 71))
        self.textEdit.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"  color: #a0d18c;\n"
"\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"  color: #2d9fd9;")
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(-10, 200, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 40pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"padding-right: 300px;\n"
"\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(parent=ChegeThemOne_1Win)
        self.checkBox.setGeometry(QtCore.QRect(440, 260, 16, 17))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label.setGeometry(QtCore.QRect(290, 220, 61, 31))
        self.label.setStyleSheet("font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_5.setGeometry(QtCore.QRect(400, 220, 91, 31))
        self.label_5.setStyleSheet("font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(parent=ChegeThemOne_1Win)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 560, 121, 41))
        self.pushButton_2.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(-10, 340, 521, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 40pt \"Times New Roman\";\n"
"background-color: grey;\n"
"color: white;\n"
"text-align: center;\n"
"padding-right: 225px;\n"
"\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_7.setGeometry(QtCore.QRect(200, 210, 51, 41))
        self.label_7.setStyleSheet("font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=ChegeThemOne_1Win)
        self.radioButton_2.setGeometry(QtCore.QRect(290, 390, 16, 17))
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_8 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_8.setGeometry(QtCore.QRect(390, 350, 51, 41))
        self.label_8.setStyleSheet("font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.label_8.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=ChegeThemOne_1Win)
        self.radioButton_3.setGeometry(QtCore.QRect(410, 390, 16, 17))
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_9 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_9.setGeometry(QtCore.QRect(270, 350, 51, 41))
        self.label_9.setStyleSheet("font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(parent=ChegeThemOne_1Win)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 560, 121, 41))
        self.pushButton_3.setStyleSheet(" background-color: #f6f6f6; /*Цвет текстового поля*/\n"
"  border-radius: 10px 10px 10px 10px; /*Закругляем уголки*/\n"
" border-radius: 20px;\n"
"  border: 1px solid #2d9fd9;\n"
"\n"
"  width: 250px;\n"
"  height: 30px;\n"
"  padding-left: 10px;\n"
"outline: none;\n"
"  border: 1px solid black;\n"
"font-weight: bold;\n"
"font:  12pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=ChegeThemOne_1Win)
        self.checkBox_2.setGeometry(QtCore.QRect(220, 260, 16, 17))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=ChegeThemOne_1Win)
        self.checkBox_3.setGeometry(QtCore.QRect(310, 260, 16, 17))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_3 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_3.setGeometry(QtCore.QRect(220, 160, 261, 31))
        self.label_3.setStyleSheet("font: 20pt \"Times New Roman\";\n"
"\n"
"text-align: center;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_10.setGeometry(QtCore.QRect(220, 300, 261, 31))
        self.label_10.setStyleSheet("font: 20pt \"Times New Roman\";\n"
"\n"
"text-align: center;\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=ChegeThemOne_1Win)
        self.label_11.setGeometry(QtCore.QRect(150, 0, 311, 31))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")

        self.retranslateUi(ChegeThemOne_1Win)
        QtCore.QMetaObject.connectSlotsByName(ChegeThemOne_1Win)

    def retranslateUi(self, ChegeThemOne_1Win):
        _translate = QtCore.QCoreApplication.translate
        ChegeThemOne_1Win.setWindowTitle(_translate("ChegeThemOne_1Win", "Chege theme one"))
        self.label_2.setText(_translate("ChegeThemOne_1Win", "Тема :"))
        self.textEdit.setHtml(_translate("ChegeThemOne_1Win", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("ChegeThemOne_1Win", "Тесты:"))
        self.label.setText(_translate("ChegeThemOne_1Win", "Один ответ"))
        self.label_5.setText(_translate("ChegeThemOne_1Win", "Несколько ответов"))
        self.pushButton_2.setText(_translate("ChegeThemOne_1Win", "Далее"))
        self.label_6.setText(_translate("ChegeThemOne_1Win", "Практика:"))
        self.label_7.setText(_translate("ChegeThemOne_1Win", "Не будет"))
        self.label_8.setText(_translate("ChegeThemOne_1Win", "Не будет"))
        self.label_9.setText(_translate("ChegeThemOne_1Win", "Будет"))
        self.pushButton_3.setText(_translate("ChegeThemOne_1Win", "Назад"))
        self.label_3.setText(_translate("ChegeThemOne_1Win", "Выберите только одно"))
        self.label_10.setText(_translate("ChegeThemOne_1Win", "Выберите только одно"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChegeThemOne_1Win = QtWidgets.QDialog()
    ui = Ui_ChegeThemOne_1Win()
    ui.setupUi(ChegeThemOne_1Win)
    ChegeThemOne_1Win.show()
    sys.exit(app.exec())
